version: "3.9"

services:
  db:
    container_name: quantex_db 
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    container_name: quantex_backend
    build:
      context: ./backend
      dockerfile: ../docker/django/Dockerfile
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./backend:/backend
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
