# Generated by Django 4.0.2 on 2022-03-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('symbol', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('baseCurrency', models.CharField(max_length=3)),
                ('region', models.CharField(max_length=128)),
                ('data', models.JSONField()),
            ],
        ),
    ]
