# Generated by Django 4.0.2 on 2022-03-16 22:00

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('symbol', models.CharField(default='', max_length=5, primary_key=True, serialize=False, unique=True)),
                ('date', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), size=None)),
                ('open', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('close', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('low', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('high', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('volume', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), size=None)),
                ('dividends', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), null=True, size=None)),
                ('stocks_splits', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Sustainability',
            fields=[
                ('symbol', models.CharField(default='', max_length=5, primary_key=True, serialize=False, unique=True)),
                ('date', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(null=True), size=None)),
                ('palmOil', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(null=True), size=None)),
                ('controversialWeapons', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(null=True), size=None)),
                ('gambling', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(null=True), size=None)),
                ('socialScore', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), size=None)),
                ('nuclear', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(null=True), size=None)),
                ('furLeather', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(null=True), size=None)),
                ('alcoholic', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(null=True), size=None)),
                ('gmo', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(null=True), size=None)),
                ('socialPercentile', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), size=None)),
                ('peerCount', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), size=None)),
                ('governanceScore', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), size=None)),
                ('environmentPercentile', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), size=None)),
                ('animalTesting', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(null=True), size=None)),
                ('tobacco', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(null=True), size=None)),
                ('totalEsg', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), size=None)),
                ('highestControversy', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), size=None)),
                ('esgPerformance', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), size=None)),
                ('coal', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(null=True), size=None)),
                ('pesticides', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(null=True), size=None)),
                ('adult', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(null=True), size=None)),
                ('smallArm', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(null=True), size=None)),
                ('militaryContract', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(null=True), size=None)),
                ('percentile', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), size=None)),
                ('governancePercentile', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('symbol', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('baseCurrency', models.CharField(max_length=3)),
                ('region', models.CharField(max_length=3)),
                ('data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantex_marketdata', to='quantex.marketdata')),
                ('sustainability', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantex_sustainability', to='quantex.sustainability')),
            ],
        ),
    ]
