# Generated by Django 4.0.2 on 2022-03-08 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quantex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantex_marketdata', to='quantex.marketdata'),
        ),
    ]
