# Generated by Django 4.0.2 on 2022-03-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='details',
            field=models.JSONField(null=True),
        ),
    ]
