# Generated by Django 4.0.2 on 2022-03-20 15:52

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quantex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('symbol', models.CharField(default='', max_length=5, primary_key=True, serialize=False, unique=True)),
                ('investments', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), size=None)),
                ('changeToLiabilities', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), size=None)),
                ('totCFInvestingActivities', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), size=None)),
                ('netBorrowings', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), size=None)),
                ('totCFinancingActivities', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), size=None)),
                ('changeToOperatingActivities', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), size=None)),
                ('netIncome', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), size=None)),
                ('changeInCash', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), size=None)),
                ('repurchaseOfStock', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), size=None)),
                ('effectOfExchangeRate', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), size=None)),
                ('totCFOperatingActivites', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), size=None)),
                ('depreciation', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), size=None)),
                ('otherCFInvestingActivites', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), size=None)),
                ('changeToAccountReceivables', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), size=None)),
                ('otherCFFinancingActivites', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), size=None)),
                ('changeToNetIncome', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), size=None)),
                ('capitalExpenditures', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), size=None)),
            ],
        ),
        migrations.AddField(
            model_name='instrument',
            name='balanceSheet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantex_balancesheet', to='quantex.balancesheet'),
        ),
    ]
