# Generated by Django 4.0.2 on 2022-03-20 15:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantex', '0002_balancesheet_instrument_balancesheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancesheet',
            name='capitalExpenditures',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='changeInCash',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='changeToAccountReceivables',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='changeToLiabilities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='changeToNetIncome',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='changeToOperatingActivities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='depreciation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='effectOfExchangeRate',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='investments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='netBorrowings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='netIncome',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='otherCFFinancingActivites',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='otherCFInvestingActivites',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='repurchaseOfStock',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='totCFInvestingActivities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='totCFOperatingActivites',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='totCFinancingActivities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), null=True, size=None),
        ),
    ]
