# Generated by Django 4.0.2 on 2022-03-20 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quantex', '0003_alter_balancesheet_capitalexpenditures_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BalanceSheet',
            new_name='CashFlow',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='balanceSheet',
        ),
        migrations.AddField(
            model_name='instrument',
            name='cashFlow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantex_cashflow', to='quantex.cashflow'),
        ),
    ]
