# Generated by Django 4.0.2 on 2022-03-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantex', '0003_remove_instrument_basecurrency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='symbol',
            field=models.CharField(max_length=7, primary_key=True, serialize=False, unique=True),
        ),
    ]
