# Generated by Django 4.0.2 on 2022-03-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quantex', '0004_rename_balancesheet_cashflow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='sustainability',
        ),
    ]
