# Generated by Django 4.0.2 on 2022-03-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantex', '0004_alter_instrument_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='symbol',
            field=models.CharField(default='', max_length=7, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='symbol',
            field=models.CharField(default='', max_length=7, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sustainability',
            name='symbol',
            field=models.CharField(default='', max_length=7, primary_key=True, serialize=False, unique=True),
        ),
    ]
