# Generated by Django 4.0.2 on 2022-03-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantex', '0005_alter_cashflow_symbol_alter_marketdata_symbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='region',
            field=models.CharField(max_length=56),
        ),
    ]
